### ISSUE TITLE
Unexpected Data Format during capturing Instagram Data

### ISSUE THREAD

**Issue by BergJakob** [digitalmethodsinitiative/zeeschuimer#27] opened 2024-02-23 07:34 UTC
Thanks for the new release, scrolling and capturing data from specific profiles does work again. But when I transfer them to 4CAT, in the results cell the following statement can be read:  "Unexpected data format for XX items. All data can be downloaded, but only data with expected format will be available to 4CAT processors; check logs for details. XX items captured." When going into detail it seems like that somehow in the ndjson-file, the format can't be recognized. 

Is this a local problem on my machine or a general bug? 

Thanks in advance!

**Comment by BergJakob** [comment] 2024-02-23 07:35
Here are the log details: 

Fri Feb 23 07:16:46 2024: Processing 'Import scraped Instagram data' started for dataset 2f52d64e80268333691f61f53f07f8df
Fri Feb 23 07:16:46 2024: Processing data
Fri Feb 23 07:16:48 2024: Writing collected data to dataset file
Fri Feb 23 07:16:48 2024: MapItemException (item 0): Unable to map item: KeyError-'full_name'
Fri Feb 23 07:16:48 2024: MapItemException (item 1): Unable to map item: KeyError-'full_name'
Fri Feb 23 07:16:48 2024: MapItemException (item 2): Unable to map item: KeyError-'full_name'
Fri Feb 23 07:16:48 2024: MapItemException (item 3): Unable to map item: KeyError-'full_name'
Fri Feb 23 07:16:48 2024: MapItemException (item 4): Unable to map item: KeyError-'full_name'
Fri Feb 23 07:16:48 2024: MapItemException (item 5): Unable to map item: KeyError-'full_name'
Fri Feb 23 07:16:48 2024: MapItemException (item 6): Unable to map item: KeyError-'full_name'
Fri Feb 23 07:16:48 2024: MapItemException (item 7): Unable to map item: KeyError-'full_name'
Fri Feb 23 07:16:48 2024: MapItemException (item 8): Unable to map item: KeyError-'full_name'
Fri Feb 23 07:16:48 2024: MapItemException (item 9): Unable to map item: KeyError-'full_name'
Fri Feb 23 07:16:48 2024: MapItemException (item 10): Unable to map item: KeyError-'full_name'
Fri Feb 23 07:16:48 2024: MapItemException (item 11): Unable to map item: KeyError-'full_name'
Fri Feb 23 07:16:48 2024: MapItemException (item 12): Unable to map item: KeyError-'full_name'
Fri Feb 23 07:16:48 2024: MapItemException (item 13): Unable to map item: KeyError-'full_name'
Fri Feb 23 07:16:48 2024: Query finished, results are available.
Fri Feb 23 07:16:48 2024: Unexpected data format for 14 items. All data can be downloaded, but only data with expected format will be available to 4CAT processors; check logs for details

**Comment by BergJakob** [comment] 2024-02-23 12:59
I`ll contact you via Email in a few mins. Thank you for the quick response.

**Comment by stijn-uva** [comment] 2024-02-23 14:46
Thanks for forwarding the data! The issue is fixed in 4CAT; Instagram changed their data structure recently and 4CAT needs to be updated accordingly. We will be releasing a new version early next week, so if you then update 4CAT you should be able to properly upload the data and export it to CSV, et cetera.

**Closed by stijn-uva** 2024-02-23 14:46 UTC
Labels: actually-4cat, platform-change

**Comment by BergJakob** [comment] 2024-02-23 14:48
Thank you!

**Comment by BergJakob** [comment] 2024-02-29 07:31
Hi @stijn-uva, is it already forseeable when the new 4CAT-Version will be published? I need scraping data for a paper and need to make some timeframe arrangements according to when I can use 4CAT again. Thanks so much in advance!

**Comment by dale-wahl** [comment] 2024-03-01 07:13
You can use the “latest” Docker tag in the .env file to use the most current version of 4cat including the above fix if you cannot wait for the release.

**Comment by stijn-uva** [comment] 2024-03-05 16:03
Hi @BergJakob, this was delayed a bit for various reasons, but version 1.40 is now available: https://github.com/digitalmethodsinitiative/4cat/releases/tag/v1.40
